<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fea</string>
		<string>feax</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*(#.*)?$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>AFDKO Features</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#special-characters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant-number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant-hexadecimal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#glyph-class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unicode-constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#afii-constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mark-anchor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#substitute</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#position</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#property-names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#deprecated-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language-constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#double-quoted-string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.function.AFDKO</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(anon(ymous)?|feature|table|lookup)\s+([a-zA-Z0-9_/]+)\s*</string>
			<key>name</key>
			<string>meta.function.AFDKO</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\s*([a-zA-Z0-9_/]+)\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.property-list.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-list-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mark-anchor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substitute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#position</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lookupfeature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#deprecated-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-hexadecimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quoted-string</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>special-characters</key>
		<dict>
			<key>match</key>
			<string>[\'\=\[\]\(\)\-\+&lt;&gt;]</string>
			<key>name</key>
			<string>keyword.other.AFDKO</string>
		</dict>
		<key>afii-constant</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(afii)([0-9]{1,10})\b</string>
			<key>name</key>
			<string>constant.other.glyphname-value.afii.AFDKO</string>
		</dict>
		<key>by-from</key>
		<dict>
			<key>match</key>
			<string>\b(by|from)\b</string>
			<key>name</key>
			<string>keyword.control.flow.AFDKO</string>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.AFDKO</string>
		</dict>
		<key>constant-number</key>
		<dict>
			<key>match</key>
			<string>\b(-|\+)?\s*[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.AFDKO</string>
		</dict>
		<key>constant-hexadecimal</key>
		<dict>
			<key>match</key>
			<string>\b(?i:(0x\h{,6}))\b</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.AFDKO</string>
		</dict>
		<key>deprecated-keywords</key>
		<dict>
			<key>match</key>
			<string>\b(exclude|include)DFLT</string>
			<key>name</key>
			<string>invalid.deprecated.AFDKO</string>
		</dict>
		<key>double-quoted-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.AFDKO</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i:(\\\h{,6}))</string>
					<key>name</key>
					<string>constant.character.escape.AFDKO</string>
				</dict>
			</array>
		</dict>
		<key>glyph-class</key>
		<dict>
			<key>match</key>
			<string>@[a-zA-Z\.0-9_-]+</string>
			<key>name</key>
			<string>storage.type.class.AFDKO</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(enum(erate)?|ignore|language(system)?|script|subtable|required|(exclude|include)_dflt|lookupflag|anchor|contourpoint|caret|cursive|device|base|mark|ligature)\b</string>
			<key>name</key>
			<string>keyword.control.AFDKO</string>
		</dict>
		<key>language-constants</key>
		<dict>
			<key>match</key>
			<string>\b(DFLT|dflt|NULL)\b</string>
			<key>name</key>
			<string>support.constant.language.AFKDO</string>
		</dict>
		<key>lookupfeature</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.function.AFDKO</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(lookup|feature)\s+([a-zA-Z0-9_]+)\s*</string>
			<key>name</key>
			<string>meta.function.AFDKO</string>
		</dict>
		<key>position</key>
		<dict>
			<key>begin</key>
			<string>\b(pos(ition)?)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.control.position.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lookupfeature</string>
				</dict>
			</array>
		</dict>
		<key>property-list-content</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\s*([a-zA-Z0-9_]\w*)\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-list-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mark-anchor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substitute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#position</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lookupfeature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#deprecated-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-hexadecimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quoted-string</string>
				</dict>
			</array>
		</dict>
		<key>property-names</key>
		<dict>
			<key>match</key>
			<string>\b(FSType|name(id)?|parameters|(HorizAxis|VertAxis)\.(Base(Tag|Script)List|MinMax)|GlyphClassDef|Attach|LigatureCaret(ByPos|ByIndex)?|FontRevision|CaretOffset|Panose|win(Ascent|Descent)|(Unicode|CodePage)Range|(X|Cap)Height|Vendor|(Weight|Width)Class|sizemenuname|(Vert)?(Typo)?(Ascender|Descender|LineGap|Origin(Advance)?Y)|ligComponent|featureNames|cvParameters|(FeatUILabel|FeatUITooltipText|SampleText|ParamUILabel|ParamUILabel)NameID|Character|Ignore(BaseGlyphs|Ligatures|Marks)|UseMarkFilteringSet|MarkAttachmentType|RightToLeft|useExtension)\b</string>
			<key>name</key>
			<string>support.type.property-name.AFDKO</string>
		</dict>
		<key>substitute</key>
		<dict>
			<key>begin</key>
			<string>\b((r)?(everse)?sub(stitute)?)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.control.substitute.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#by-from</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lookupfeature</string>
				</dict>
			</array>
		</dict>
		<key>include-statement</key>
		<dict>
			<key>begin</key>
			<string>\b(include\s*\()</string>
			<key>end</key>
			<string>(\))\s*;</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.AFDKO</string>
				</dict>
			</dict>
		</dict>
		<key>mark-anchor</key>
		<dict>
			<key>begin</key>
			<string>\b((mark|base)Class|anchorDef)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.control.mark-anchor.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
			</array>
		</dict>
		<key>unicode-constant</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.AFDKO</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((uni)[0-9a-fA-F]{4}+|(u)([0-9a-fA-F]{5}+|[0-9a-fA-F]{6}+))\b</string>
			<key>name</key>
			<string>constant.other.glyphname-value.unicode.AFDKO</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.AFDKO</string>
	<key>uuid</key>
	<string>4E852A29-A2DA-4614-ABA0-DAE269E6492B</string>
</dict>
</plist>
