<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fea</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*(#.*)?$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>AFDKO Features</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment-line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant-number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#glyph-class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unicode-constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#afii-constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#substitute</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#position</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#property-names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#deprecated-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language-constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single-quoted-string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#double-quoted-string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.function.AFDKO</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(anon(ymous)?|feature|table|lookup)\s+([a-zA-Z0-9_]\w*)\s*</string>
			<key>name</key>
			<string>meta.function.AFDKO</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\s*([a-zA-Z0-9_]\w*)\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.property-list.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-list-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substitute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#position</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lookupfeature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#deprecated-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quoted-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quoted-string</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>afii-constant</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(afii)([0-9]{1,10})\b</string>
			<key>name</key>
			<string>constant.other.glyphname-value.afii.AFDKO</string>
		</dict>
		<key>by-from</key>
		<dict>
			<key>match</key>
			<string>\b(by|from)\b</string>
			<key>name</key>
			<string>keyword.control.flow.AFDKO</string>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.AFDKO</string>
		</dict>
		<key>constant-number</key>
		<dict>
			<key>match</key>
			<string>\b(-|\+)?\s*[0-9]+(\.[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.AFDKO</string>
		</dict>
		<key>deprecated-keywords</key>
		<dict>
			<key>match</key>
			<string>\b(exclude|include)DFLT</string>
			<key>name</key>
			<string>invalid.deprecated.AFDKO</string>
		</dict>
		<key>double-quoted-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.AFDKO</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.AFDKO</string>
				</dict>
			</array>
		</dict>
		<key>glyph-class</key>
		<dict>
			<key>match</key>
			<string>@[a-zA-Z\.0-9_-]+</string>
			<key>name</key>
			<string>storage.type.class.AFDKO</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(enum(erate)?|ignore|include|language(system)?|script|subtable|required|(exclude|include)_dflt|lookupflag|anchor|caret|cursive|device|Ignore(BaseGlyphs|Ligatures|Marks)|UseMarkFilteringSet|MarkAttachmentType|mark|RightToLeft)\b</string>
			<key>name</key>
			<string>keyword.control.AFDKO</string>
		</dict>
		<key>language-constants</key>
		<dict>
			<key>match</key>
			<string>\b(DFLT|dflt|NULL)\b</string>
			<key>name</key>
			<string>support.constant.language.AFKDO</string>
		</dict>
		<key>lookupfeature</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.function.AFDKO</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(lookup|feature)\s+([a-zA-Z0-9_]\w*)\s*</string>
			<key>name</key>
			<string>meta.function.AFDKO</string>
		</dict>
		<key>position</key>
		<dict>
			<key>begin</key>
			<string>\b(pos(ition)?)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.control.position.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
			</array>
		</dict>
		<key>property-list-content</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\s*([a-zA-Z0-9_]\w*)\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-list-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substitute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#position</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lookupfeature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#deprecated-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quoted-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quoted-string</string>
				</dict>
			</array>
		</dict>
		<key>property-names</key>
		<dict>
			<key>match</key>
			<string>\b(FSType|nameid|parameters|(HorizAxis|VertAxis)\.(Base(Tag|Script)List|MinMax)|GlyphClassDef|Attach|LigatureCaret|FontRevision|CaretOffset|Ascender|Descender|LineGap|Panose|Typo(Ascender|Descender|LineGap)|win(Ascent|Descent)|UnicodeRange|CodePageRange|XHeight|CapHeight|Vendor|sizemenuname|VertTypo(Ascender|Descender|LineGap|Origin(Advance)?Y))\b</string>
			<key>name</key>
			<string>support.type.property-name.AFDKO</string>
		</dict>
		<key>single-quoted-string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.AFDKO</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.single.AFDKO</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.AFDKO</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.AFDKO</string>
				</dict>
			</array>
		</dict>
		<key>substitute</key>
		<dict>
			<key>begin</key>
			<string>\b((r)?(everse)?sub(stitute)?)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.AFDKO</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.control.substitute.AFDKO</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#by-from</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glyph-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unicode-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afii-constant</string>
				</dict>
			</array>
		</dict>
		<key>unicode-constant</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.AFDKO</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.AFDKO</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((uni)[0-9a-fA-F]{4}+|(u)([0-9a-fA-F]{5}+|[0-9a-fA-F]{6}+))\b</string>
			<key>name</key>
			<string>constant.other.glyphname-value.unicode.AFDKO</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.AFDKO</string>
	<key>uuid</key>
	<string>4E852A29-A2DA-4614-ABA0-DAE269E6492B</string>
</dict>
</plist>
